### ISSUE TITLE
Wrong answer is not shown on course revisit

### ISSUE THREAD

**Issue by mmitic86** [adaptlearning/adapt-contrib-textInput#125]
Adapt FW v5.22.6 | Text input v7.2.1

When user type wrong answer, after revisiting course that answer is not shown, insted asterisks are shown. This is not the case with correct answer. I'm not sure is this regular behavior or not.
It is happening on scorm environment (revisit) or on local environment, /scorm_test_harness.html, (on page refresh). 
In my case component is used as an assessment question where show "Show marking" is enabled in assessment extension.

Correct answered question and revisited shows this (correct behavior):
![image](https://user-images.githubusercontent.com/47385152/216344010-76c49201-ea2e-49be-b870-8a37781d5de4.png)

Wrong answered question and revisited shows this:
![image](https://user-images.githubusercontent.com/47385152/216343727-b24abab0-2679-4543-b881-55d9419650d4.png)

**Comment by oliverfoster** [comment]
Adapt cannot store text on the LMS, there isn't enough space, so the user's answer isn't actually restored, only their correctness.

**Comment by mmitic86** [comment]
I see. Thank you for your answer.

**Comment by oliverfoster** [comment]
### For reference

Save:
https://github.com/adaptlearning/adapt-contrib-textInput/blob/56b785ca1055a856babd002ac122a2c26b3df23c/js/textInputModel.js#L86-L88

Restore:
https://github.com/adaptlearning/adapt-contrib-textInput/blob/56b785ca1055a856babd002ac122a2c26b3df23c/js/textInputModel.js#L41-L54
