### ISSUE TITLE
Validation issues for generic _answers in authoring tool schema

### ISSUE THREAD

**Issue by dancgray** [adaptlearning/adapt-contrib-textInput#59]
There should be the same number of items in the generic _answers array as in the _items array. I don't think it is currently possible to validate this in the authoring tool schemas.

It may be better to refactor this functionality, e.g "_answersInAnyOrder": true/false.

**Comment by dancgray** [comment]
refers to this part of the JSON:

_answers

*Optional *

This allows generic answers, which are not dependant on order to be specified, allowing the learner to give the correct answers in any order, and still be marked correct. This attribute expects a 2-dimensional array:

“_answers”: [
   [“one”,1],
   [“two”,2],
   [“three”,3]   
]

**Comment by guywillis** [comment]
This issue was moved to adaptlearning/adapt_framework#866
