### ISSUE TITLE
duplicate id references

### ISSUE THREAD

**Issue by chucklorenz** [adaptlearning/adapt-contrib-textInput#75]
_id is not being found. Notice how ids have values of "-0" instead of "c-105-0". Affects inputs and their labels:

![image](https://cloud.githubusercontent.com/assets/9489014/10298816/6d8af7ce-6ba8-11e5-85d4-e083ac7448ef.png)

Consequently, duplicate ids are being created.

**Comment by dancgray** [comment]
@chucklorenz can this be closed now?

**Comment by chucklorenz** [comment]
Yes, Dan.
